"""Orders tables

Revision ID: 848da2d42120
Revises: fdb64bba0380
Create Date: 2021-02-14 15:17:24.739471

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '848da2d42120'
down_revision = 'fdb64bba0380'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    pass


def downgrade_():
    pass


def upgrade_ordersDB():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fulfillment_warehouse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('enabled', mssql.BIT(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('order_line_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Unicode(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('order_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Unicode(length=20), nullable=False),
    sa.Column('description', sa.Unicode(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sales_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Unicode(length=100), nullable=False),
    sa.Column('code', sa.Unicode(length=20), nullable=False),
    sa.Column('service_id', sa.Unicode(length=50), nullable=True),
    sa.Column('balanceable', mssql.BIT(), server_default='0', nullable=False),
    sa.Column('enabled', mssql.BIT(), server_default='1', nullable=False),
    sa.Column('product_alias_group', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_cross_insert', mssql.BIT(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('service_id')
    )
    op.create_table('ship_service_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Unicode(length=20), nullable=False),
    sa.Column('description', sa.Unicode(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Unicode(length=50), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('ship_name', sa.Unicode(length=500), nullable=False),
    sa.Column('ship_phone', sa.Unicode(length=100), nullable=True),
    sa.Column('ship_email', sa.Unicode(length=500), nullable=True),
    sa.Column('ship_address', sa.Unicode(length=500), nullable=False),
    sa.Column('ship_address_2', sa.Unicode(length=500), nullable=True),
    sa.Column('ship_city', sa.Unicode(length=500), nullable=True),
    sa.Column('ship_postal_code', sa.Unicode(length=100), nullable=True),
    sa.Column('ship_state', sa.Unicode(length=500), nullable=True),
    sa.Column('ship_country', sa.Unicode(length=500), nullable=False),
    sa.Column('buyer_name', sa.Unicode(length=500), nullable=True),
    sa.Column('buyer_phone', sa.Unicode(length=100), nullable=True),
    sa.Column('buyer_email', sa.Unicode(length=500), nullable=True),
    sa.Column('buyer_address', sa.Unicode(length=500), nullable=True),
    sa.Column('buyer_address_2', sa.Unicode(length=500), nullable=True),
    sa.Column('buyer_city', sa.Unicode(length=500), nullable=True),
    sa.Column('buyer_state', sa.Unicode(length=500), nullable=True),
    sa.Column('buyer_postal_code', sa.Unicode(length=100), nullable=True),
    sa.Column('buyer_country', sa.Unicode(length=500), nullable=True),
    sa.Column('sales_channel_id', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('total_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('order_status_id', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.Unicode(length=20), server_default='Pending', nullable=False),
    sa.Column('referring_order', sa.Integer(), nullable=True),
    sa.Column('is_prime', mssql.BIT(), server_default='0', nullable=False),
    sa.Column('is_premium', mssql.BIT(), server_default='0', nullable=False),
    sa.Column('shipping_priority', sa.Unicode(length=128), nullable=True),
    sa.ForeignKeyConstraint(['order_status_id'], ['order_status.id'], ),
    sa.ForeignKeyConstraint(['sales_channel_id'], ['sales_channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=159), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('qty_ordered', sa.Integer(), nullable=False),
    sa.Column('qty_shipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency_code', sa.Unicode(length=3), nullable=False),
    sa.Column('shipping_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping_tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('line_type', sa.Unicode(length=10), nullable=True),
    sa.Column('purchase_order_number', sa.Unicode(length=128), nullable=True),
    sa.Column('order_line_status_id', sa.Integer(), nullable=True),
    sa.Column('exported', mssql.BIT(), server_default='0', nullable=False),
    sa.Column('date_exported', sa.DateTime(), nullable=True),
    sa.Column('username', sa.Unicode(length=256), nullable=True),
    sa.Column('notes', sa.Unicode(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('processed_date', sa.DateTime(), nullable=True),
    sa.Column('promise_date', sa.DateTime(), nullable=True),
    sa.Column('fulfillment_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('is_premium', mssql.BIT(), server_default='0', nullable=False),
    sa.Column('shipping_priority', sa.Unicode(length=128), nullable=True),
    sa.ForeignKeyConstraint(['fulfillment_warehouse_id'], ['fulfillment_warehouse.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['order_line_status_id'], ['order_line_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_ordersDB():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_line')
    op.drop_table('order')
    op.drop_table('ship_service_level')
    op.drop_table('sales_channel')
    op.drop_table('order_status')
    op.drop_table('order_line_status')
    op.drop_table('fulfillment_warehouse')
    # ### end Alembic commands ###

