import urllib
#static_folder = "static"
# base64.b64encode(os.urandom(64)).decode("ascii")
SECRET_KEY=""

HOME_PAGE = "/trades"

database='BinanceLeaderTrades'
# conn strings
#  *** on windows: ***
# localhost default instance:
SERVER_CONN_STR = ""

SQLALCHEMY_BINDS = {
    'mainDB':        SERVER_CONN_STR.format(database=database.lower()),
}

SQLALCHEMY_TRACK_MODIFICATIONS = False
# SQLALCHEMY_ECHO = True

# empty = pooling disabled
TRADE_POOLING_ENDPOINT = ""  # "http://127.0.0.1:5055/process_traders"

#gooseai
#OPENAI_API_KEY = ""
#OPENAI_BASE_ADDRESS = "https://api.goose.ai/v1"
#OPENAI_DEFAULT_ENGINE = "gpt-neo-20b" # temp = 0.25
#OPENAI_DEFAULT_TEMPERATURE = 0.25
##OPENAI_DEFAULT_ENGINE = "fairseq-6-7b" # temp 0.05
##OPENAI_DEFAULT_ENGINE = "gpt-j-6b" 

OPENAI_API_KEY = ""
OPENAI_BASE_ADDRESS = "https://api.openai.com/v1"
OPENAI_DEFAULT_ENGINE = "text-davinci-002" 
OPENAI_DEFAULT_TEMPERATURE = 0.0


USE_SAFETY_CLASSIFIER = True

